- name: Add repository which contains Oracle Java 11
  apt_repository:
    repo: ppa:linuxuprising/java

- name: Select Oracle license
  shell: echo debconf shared/accepted-oracle-license-v1-2 select true | sudo debconf-set-selections
  changed_when: false

- name: Install Oracle Java 11
  apt:
    name={{ item }}
    state=present
    force=yes
  with_items:
    - oracle-java11-installer

- name: Set JAVA_HOME environment variable
  shell: sudo echo "JAVA_HOME=/usr/lib/jvm/java-11-oracle" >> /etc/environment
