- name: Add Docker key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add docker APT repository
  apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: Install Docker, Docker Compose and its dependencies
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - docker-ce
    - docker-compose

- name: Add users to the Docker group (so that user would be able to run Docker without sudo)
  user:
    name: '{{ item }}'
    groups: 'docker'
    append: 'yes'
  with_items: '{{ users_list }}'
  when: 'users_list is defined'

